# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='estado_vaca',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='tipo',
        ),
        migrations.AddField(
            model_name='animal',
            name='estado_animal',
            field=models.CharField(choices=[('Pre\xf1ada', 'Pre\xf1ada'), ('Produciendo', 'Produciendo'), ('No Produciendo', 'No Produciendo')], default='No Produciendo', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='etapa',
            field=models.CharField(choices=[('Ternera', 'Ternera'), ('Ternero', 'Ternero'), ('Novilla', 'Novilla'), ('Novillo', 'Novillo'), ('Vaca', 'Vaca'), ('Toro', 'Toro')], default='Vaca', max_length=10),
        ),
    ]
