# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0004_auto_20180819_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='estado_animal',
            new_name='estado',
        ),
    ]
