# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion_numerica', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=10)),
                ('foto', models.CharField(max_length=10)),
                ('etapa', models.CharField(choices=[('Ternera', 'Ternera'), ('Ternero', 'Ternero'), ('Novilla', 'Novilla'), ('Novillo', 'Novillo'), ('Vaca', 'Vaca'), ('Toro', 'Toro')], default='Vaca', max_length=10)),
                ('estado', models.CharField(choices=[('Pre\xf1ada', 'Pre\xf1ada'), ('Produciendo', 'Produciendo'), ('No Produciendo', 'No Produciendo')], default='No Produciendo', max_length=20)),
                ('cantidad_partos', models.IntegerField()),
            ],
        ),
    ]
