# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_registro_produc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_produc',
            name='tipo_produccion',
        ),
        migrations.AddField(
            model_name='registro_produc',
            name='produccion_diaria',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], default='Individual', max_length=20),
        ),
    ]
