# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20180819_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro_produc',
            old_name='tipo',
            new_name='unidad_de_medida',
        ),
    ]
