# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produccion_lactea_grupal', models.CharField(choices=[('D\xeda', 'D\xeda'), ('Semana', 'Semana'), ('Mes', 'Mes'), ('A\xf1o', 'A\xf1o')], default='D\xeda', max_length=10)),
            ],
        ),
    ]
