# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produccion_diaria', models.CharField(choices=[('Individual', 'Individual'), ('Grupal', 'Grupal')], default='Individual', max_length=20)),
                ('fecha_produccion', models.DateField()),
                ('cantidad_producida', models.IntegerField()),
                ('unidad_de_medida', models.CharField(choices=[('Botellas', 'Botellas'), ('Litros', 'Litros'), ('Galones', 'Galones')], default='Botellas', max_length=10)),
            ],
        ),
    ]
