# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animal', '0001_initial'),
        ('Produccion', '0002_registro_produccion_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_produccion',
            name='animal',
        ),
        migrations.AddField(
            model_name='registro_produccion',
            name='Animales',
            field=models.ManyToManyField(to='Animal.Animal'),
        ),
    ]
