# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pacas', models.IntegerField()),
                ('cantidad_carretillos', models.IntegerField()),
                ('cantidad_palas', models.IntegerField()),
                ('cantidad_desparasitantes', models.IntegerField()),
                ('cantidad_ordenadoras', models.IntegerField()),
                ('cantidad_estanon_miel', models.IntegerField()),
            ],
        ),
    ]
